hello2/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'home', 'about', 'math', 'lottery', controller: 'pages'

  get 'pages2/home'
  get 'pages2/about'

end

hello2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

hello2/app/controllers/pages2_controller.rb
class Pages2Controller < ApplicationController
  def home
  end

  def about
  end
end

hello2/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  	render 'pages/home'
  end

  def about
  	@me = params[:name]
  	@age= params['age']
  	# @me = params['name']
  	# render 'pages/about'

  	# change layout for backstage
	  # render 'pages/about', layout: 'admin'
  end

  def math
  	render 'pages/math'
  end

  def lottery
  	@numbers = (1..46).to_a.sample(6)
  	# render 'pages/lottery'  	
  end

end

hello2/app/helpers/application_helper.rb
module ApplicationHelper
end

hello2/app/helpers/navbar_helper.rb
# app/helpers/navbar_helper.rb
module NavbarHelper
	def nav_li text, path
		active = request.path == path ? :active : nil
		content_tag :li, link_to(text, path), class: active
	end
end

hello2/app/helpers/pages2_helper.rb
module Pages2Helper
end

hello2/app/helpers/pages_helper.rb
module PagesHelper
end

hello2/app/helpers/product_helper.rb
# app/helpers/products_helper.rb
module ProductHelper
	def product_li product
		hot_class = @product.hot? ? :hot : nil
		content_tag :li, product.name, class: hot_class
	end		
end

hello2/app/views/albums/_album.html.erb
<!-- app/views/albums/_album.html.erb -->
<div class="thumbnail">
	<img src="<%= image %>" alt="..." />
	<div class="caption">
		<h3><%= title %></h3>
		<p><%= summary %></p>
	</div>
</div>			

hello2/app/views/layouts/admin.html.erb
<!-- app/views/layout/admin.html.erb -->
<html>
	<head><title>Backstage</title></head>
	<body>
		<h1>Backstage</h1>
		<%= yield %>
	</body>
</html>	

hello2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hello2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<ul>
<%= render 'shared/navbar', line_number:3 %>
<%#= render 'pages/navbar' %>
</ul>


<%= yield %>
</body>
</html>

hello2/app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>
<h2> Welcome! I'm <%= @me %>, and <%= @age %> years old.</h2>

hello2/app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<%= render 'albums/album', title: 'naruto', summary: 'This is naruto', image: 'naruto.jpg', alter: '...' %>
<%= render 'albums/album', title: 'saei', summary: 'This is saei', image: 'saei.jpg', alter: '...' %>

hello2/app/views/pages/lottery.html.erb
<ul>
<% (1..46).to_a.sample(6).each do |i| %>
	<li><%= i %></li>
<% end %>
</ul>

<ul>
<% @numbers.each do |i| %>
	<li><%= i %></li>
<% end %>
</ul>	

hello2/app/views/pages/math.html.erb
<!-- app/views/pages/math.html.erb -->

<% a = 1 %>
<% b = 2 %>
<%# c = 1 %>

<h1><%= a + b %></h1>
<h1><%%= a + b %></h1>

<% if rand > 0.5 %>
<h1>Oh! Big</h1>
<% else %>
<h1>Oh! Small</h1>
<% end %>

<% user_signed_in = true %>
<% if user_signed_in %>
	<h1>Welcome back</h1>
<% else %>
	<h1><a href="/sign_in">Please log in</a></h1>
<% end %>

<ul>
<% 7.times do |i| %>
	<li><%= i %></li>
<% end %>
</ul>

hello2/app/views/pages2/about.html.erb
<h1>Pages2#about</h1>
<p>Find me in app/views/pages2/about.html.erb</p>

hello2/app/views/pages2/home.html.erb
<h1>Pages2#home</h1>
<p>Find me in app/views/pages2/home.html.erb</p>

hello2/app/views/shared/_navbar.html.erb
<!-- app/views/shared/_navbar.html.erb -->
<ul>
	<li><a href="<%= root_path %>">Home Page (old)</a></li>
	<li><a href="<%= about_path %>">About (old)</a></li>
	<li><a href="<%= lottery_path %>">Lottery (old)</a></li>
</ul>

<ul>
<%= nav_li "Index Page", root_path %>
<%= nav_li "About Page", about_path %>
<%= nav_li "Lottery Page", lottery_path %>
</ul>

<%#= product_li "GG" %>

<% line_number.times do %>
<hr>
<% end %>